/* Generated by Snowball 2.0.0 - https://snowballstem.org/ */


#include "steminternal.h"

namespace Xapian {

class InternalStemGreek : public SnowballStemImplementation {
    unsigned char I_test1;
    int r_step7();
    int r_step6();
    int r_step5m();
    int r_step5l();
    int r_step5k();
    int r_step5j();
    int r_step5i();
    int r_step5h();
    int r_step5g();
    int r_step5f();
    int r_step5e();
    int r_step5d();
    int r_step5c();
    int r_step5b();
    int r_step5a();
    int r_step4();
    int r_step3();
    int r_step2d();
    int r_step2c();
    int r_step2b();
    int r_step2a();
    int r_step1();
    int r_steps10();
    int r_steps9();
    int r_steps8();
    int r_steps7();
    int r_steps6();
    int r_steps5();
    int r_steps4();
    int r_steps3();
    int r_steps2();
    int r_steps1();
    int r_has_min_length();
    int r_tolower();

  public:

    InternalStemGreek();
    ~InternalStemGreek();
    int stem();
    std::string get_description() const;
};

}
